# -*- coding: utf-8 -*-

THREAD = 'thread'
URL = 'http://%s.diary.ru/p%s.htm'
F_P = 'fandomnaya-pravda'
P_C = 'pravdoruboklon'
FROM = '&from='
NO_POST = 'no post'

FOLDER_POSTFIX = '_threads/'
CREEPY = 'creepy'
FANFICTION = 'fanfiction'
SOCIAL = 'social'
ROLEPLAY = 'roleplay'
RSYA = 'rsya'
FEMSLASH = 'femslash'
O_E = 'o_e'
SOCIONICS = 'socionics'
KINKS = 'kinks'
MISC = 'misc'
